name = "ai-breed-challenge-game"
compatibility_date = "2024-04-25"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

[env.production]
compatibility_date = "2024-04-25"

[[r2_buckets]]
binding = 'BREED_BUCKET'
bucket_name = 'breed-predict-game'

[[env.production.r2_buckets]]
binding = 'BREED_BUCKET'
bucket_name = 'breed-predict-game'
